## 10

In [3]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("numpy array")
print(data)
print("___________________________________")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("row sum")
print(totalr)
print("column sum")
print(totalc)
print("___________________________________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("row mean")
print(meanr)
print("column mean")
print(meanc)
print("___________________________________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("row std")
print(stdr)
print("column std")
print(stdc)



numpy array
[[1 2 3]
 [4 5 6]]
___________________________________
row sum
[ 6 15]
column sum
[5 7 9]
___________________________________
row mean
[2. 5.]
column mean
[2.5 3.5 4.5]
___________________________________
row std
[0.81649658 0.81649658]
column std
[1.5 1.5 1.5]
